admin.copperheadcreations.com/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using admin.copperheadcreations.com.Logic;
using admin.copperheadcreations.com.Models;
using Microsoft.AspNetCore.Mvc;

namespace admin.copperheadcreations.com.Controllers
{
    public class NewsController : Controller
    {

        private readonly dbcopperheadContext _context;

        public NewsController(dbcopperheadContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            if (!Authenticate.Check(_context, HttpContext))
            {
                return RedirectToAction("Logout", "Home");
            }

            NewsListViewModel model = new NewsListViewModel();

            List<NewsModel> List = new List<NewsModel>();


            var query = _context.News.Where(a => a.WebsiteId == 1).OrderByDescending(a => a.Date);

            foreach (var row in query)
            {
                NewsModel Article = new NewsModel
                {
                    Id = row.Id,
                    Slug = row.Slug,
                    Published = Convert.ToBoolean(row.Published),
                    Title = row.Title,
                    Content = row.Content,
                    Author = row.Author,
                    Date = row.Date,
                    PreviewText = row.PreviewText,
                    TypeId = row.TypeId
                };
                List.Add(Article);
            }

            model.List = List;
            return View(model);
        }

        public IActionResult Create()
        {
            if (!Authenticate.Check(_context, HttpContext))
            {
                return RedirectToAction("Logout", "Home");
            }

            List<NewsTypeModel> List = new List<NewsTypeModel>();
            var query = _context.NewsType.Where(a => a.WebsiteId == 1).OrderByDescending(a => a.Id);
            foreach (var row in query)
            {
                NewsTypeModel NewsType = new NewsTypeModel
                {
                    Id = row.Id,
                    TypeTag = row.TypeTag,
                    TypeTitle = row.TypeTitle
                };
                List.Add(NewsType);
            }

            NewsModel Article = new NewsModel
            {
                WebsiteId = 1,
            };

            NewsEditViewModel Model = new NewsEditViewModel {
                Edit = false,
                TypeList = List,
                News = Article
            };


            return View(Model);
        }

        public IActionResult Edit(int id)
        {

            if (!Authenticate.Check(_context, HttpContext))
            {
                return RedirectToAction("Logout", "Home");
            }

            List<NewsTypeModel> List = new List<NewsTypeModel>();
            var newstype_query = _context.NewsType.Where(a => a.WebsiteId == 1).OrderByDescending(a => a.Id);

            

            foreach (var row in newstype_query)
            {
                NewsTypeModel NewsType = new NewsTypeModel
                {
                    Id = row.Id,
                    TypeTag = row.TypeTag,
                    TypeTitle = row.TypeTitle
                };
                List.Add(NewsType);
            }

            var article_query = _context.News.Where(a => a.WebsiteId == 1 && a.Id == id).FirstOrDefault();

            if(article_query == null)
            {
                return RedirectToAction("Index");
            }

            NewsModel Article = new NewsModel
            {
                Id = article_query.Id,
                WebsiteId = article_query.WebsiteId,
                Slug = article_query.Slug,
                Published = Convert.ToBoolean(article_query.Published),
                Title = article_query.Title,
                Content = article_query.Content,
                Author = article_query.Author,
                Date = article_query.Date,
                PreviewText = article_query.PreviewText,
                TypeId = article_query.TypeId
            };

            NewsEditViewModel Model = new NewsEditViewModel
            {
                Edit = false,
                TypeList = List,
                News = Article
            };

            return View(Model);
        }

        public IActionResult Delete(int id)
        {
            if (!Authenticate.Check(_context, HttpContext))
            {
                return RedirectToAction("Logout", "Home");
            }

            var Article = _context.News.Where(b => b.Id == id).FirstOrDefault();
            if (Article != null)
            {
                _context.News.Remove(Article);
                _context.SaveChanges();
            }


            return RedirectToAction("Index");
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreatePost(NewsEditViewModel article)
        {
            using (var context = new dbcopperheadContext())
            {
                string author;
                if (article.News.Author == null)
                {
                    author = "";
                }
                else
                {
                    author = article.News.Author;
                }

                var newpost = new News()
                {
                    Title = article.News.Title,
                    WebsiteId = article.News.WebsiteId,
                    Slug = article.News.Slug,
                    Author = author,
                    Published = Convert.ToSByte(article.News.Published),
                    Date = article.News.Date,
                    PreviewText = article.News.PreviewText,
                    Content = article.News.Content,
                    TypeId = article.News.TypeId
                };
                context.News.Add(newpost);
                context.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditPost(NewsEditViewModel article)
        {
            using (var context = new dbcopperheadContext())
            {

                string author;
                if (article.News.Author == null)
                {
                    author = "";
                }
                else
                {
                    author = article.News.Author;
                }
                var editPost = new News()
                {
                    Id = article.News.Id,
                    Title = article.News.Title,
                    WebsiteId = article.News.WebsiteId,
                    Slug = article.News.Slug,
                    Author = author,
                    Published = Convert.ToSByte(article.News.Published),
                    Date = article.News.Date,
                    PreviewText = article.News.PreviewText,
                    Content = article.News.Content,
                    TypeId = article.News.TypeId
                };
                context.News.Update(editPost);
                context.SaveChanges();
            }

            return RedirectToAction("Index");
        }
    }
}

admin.copperheadcreations.com/Views/News/Create.cshtml
@model admin.copperheadcreations.com.Models.NewsEditViewModel
<section class="button__container">
    <a asp-controller="News" asp-action="Index" class="fancy__button fancy__button__dark button__spacer">Back</a>
</section>
<section class="container news__form">
    <form class="fancy__form color__grey bg__white" asp-action="CreatePost" asp-controller="News" method="post">

        <input asp-for="News.WebsiteId" hidden />

        <div class="form__row x30" id="Title">
            <input asp-for="News.Title" required />
            <label asp-for="News.Title"></label>
            <div class="after"></div>
        </div>
        <div class="form__row x30" id="Slug">
            <input asp-for="News.Slug" required />
            <label asp-for="News.Slug"></label>
            <div class="after"></div>
        </div>

        <div class="form__row x100">
            <input asp-for="News.PreviewText" required />
            <label asp-for="News.PreviewText"></label>
            <div class="after"></div>
        </div>

        <div class="form__row x30">
            <input asp-for="News.Author" />
            <label asp-for="News.Author"></label>
            <div class="after"></div>
        </div>

        <div class="form__row static static">
            <input class="xUnset" asp-for="News.Published" />
            <label asp-for="News.Published"></label>
        </div>

        <div class="form__row static x20">
            <input asp-for="News.Date" required type="date" />
            <label asp-for="News.Date"></label>
            <div class="after"></div>
        </div>

        <div class="form__row static x20">
            <select asp-for="News.TypeId" required>
                <option value="">--- select ----</option>
                @foreach (var i in Model.TypeList)
                {
                    <option value="@i.Id">@i.TypeTitle</option>
                }
            </select>
            <label asp-for="News.TypeId"></label>
            <div class="after"></div>
        </div>


        <textarea asp-for="News.Content" id="Editor-Content" hidden></textarea>



        <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">

        <!-- Create the editor container -->
        <div id="editor" class="form__editor">

        </div>
        <!-- Include the Quill library -->
        <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>



        <div class="form__row x10">
            <button>Submit</button>
        </div>

    </form>
</section>

admin.copperheadcreations.com/Views/News/Edit.cshtml
@model admin.copperheadcreations.com.Models.NewsEditViewModel
<section class="button__container">
    <a asp-controller="News" asp-action="Index" class="fancy__button fancy__button__dark button__spacer">Back</a>
</section>
<section class="container news__form">
    <form class="fancy__form color__grey bg__white" asp-action="EditPost" asp-controller="News" method="post">
        <input asp-for="News.Id" hidden />
        <input asp-for="News.WebsiteId" hidden />

        <div class="form__row x30" id="Title">
            <input asp-for="News.Title" required />
            <label asp-for="News.Title"></label>
            <div class="after"></div>
        </div>
        <div class="form__row x30" id="Slug">
            <input asp-for="News.Slug" required />
            <label asp-for="News.Slug"></label>
            <div class="after"></div>
        </div>

        <div class="form__row x100">
            <input asp-for="News.PreviewText" required />
            <label asp-for="News.PreviewText"></label>
            <div class="after"></div>
        </div>

        <div class="form__row x30">
            <input asp-for="News.Author" />
            <label asp-for="News.Author"></label>
            <div class="after"></div>
        </div>

        <div class="form__row static static align__left">
            <input class="xUnset" asp-for="News.Published" />
            <label asp-for="News.Published"></label>
        </div>

        <div class="form__row static x20">
            <input asp-for="News.Date" required type="date" />
            <label asp-for="News.Date"></label>
            <div class="after"></div>
        </div>

        <div class="form__row static x20">
            <select asp-for="News.TypeId" required>
                <option value="">--- select ----</option>
                @foreach (var i in Model.TypeList)
                {
                    <option value="@i.Id">@i.TypeTitle</option>
                }
            </select>
            <label asp-for="News.TypeId"></label>
            <div class="after"></div>
        </div>


        <textarea asp-for="News.Content" id="Editor-Content" hidden></textarea>



        <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">

        <!-- Create the editor container -->
        <div id="editor" class="form__editor">
            @Html.Raw(Model.News.Content)
        </div>
        <!-- Include the Quill library -->
        <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>



        <div class="form__row x10">
            <button>Submit</button>
        </div>

    </form>
</section>

admin.copperheadcreations.com/Views/News/Index.cshtml
@model admin.copperheadcreations.com.Models.NewsListViewModel


<section class="container button__container">
    <a class="generic_button" asp-controller="News" asp-action="Create">Create New Article</a>
</section>
<section class="container">
    <div class="table">
        <div class="table__row table__header">
            <div class="table__cell x25">Title</div>
            <div class="table__cell x30">Slug</div>
            <div class="table__cell x10">Published</div>
            <div class="table__cell x20">Date</div>
            <div class="table__cell x5">Preview</div>
            <div class="table__cell x5">Edit</div>
            <div class="table__cell x5">Delete</div>
        </div>
        @foreach (var u in Model.List)
        {
    <div class="table__row">
        <div class="table__cell x25">@u.Title</div>
        <div class="table__cell x30">/@u.Slug</div>
        <div class="table__cell x10 published">
            @if (Convert.ToBoolean(u.Published))
            {<i class="fas fa-check-square"></i> }
            else
            {
                <i class="fas fa-window-close"></i>
            }
        </div>
        <div class="table__cell x20">@u.Date</div>
        <a asp-controller="Preview" asp-action="Article" asp-route-id="@u.Slug" class="table__cell x5 generic_edit"><i class="fas fa-eye"></i></a>
        <a asp-controller="News" asp-action="Edit" asp-route-id="@u.Id" class="table__cell x5 generic_edit"><i class="fas fa-edit"></i></a>
        <a asp-controller="News" asp-action="Delete" asp-route-id="@u.Id" class="table__cell x5 generic_delete"><i class="fas fa-trash-alt"></i></a>
    </div>
        }

    </div>
</section>
<style>
    .published{
        text-align:center;
    }
</style>