admin.copperheadcreations.com/Models/LawViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace admin.copperheadcreations.com.Models
{
    public class LawViewModel
    {
        public List<LawModel> List { get; set; }
    }
}

admin.copperheadcreations.com/Controllers/LawController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using admin.copperheadcreations.com.Logic;
using admin.copperheadcreations.com.Models;
using Microsoft.AspNetCore.Mvc;

namespace admin.copperheadcreations.com.Controllers
{
    public class LawController : Controller
    {
        private readonly dbcopperheadContext _context;

        public LawController(dbcopperheadContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            if (!Authenticate.Check(_context, HttpContext))
            {
                return RedirectToAction("Logout", "Home");
            }

            LawViewModel Model = new LawViewModel();
                
            List<LawModel> List = new List<LawModel>();


            var query = _context.Law.Where(a => a.WebsiteId == 1);

            foreach (var row in query)
            {
                LawModel Law = new LawModel
                {
                    Id = row.Id,
                    WebsiteId = row.WebsiteId,
                    Title = row.Title,
                    Slug = row.Slug,
                    Icon = row.Icon,
                    ShortDesc = row.ShortDesc,
                    Description = row.Description,
                };
                List.Add(Law);
            }

            Model.List = List;

            return View(Model);
        }

        public IActionResult Create()
        {

            if (!Authenticate.Check(_context, HttpContext))
            {
                return RedirectToAction("Logout", "Home");
            }

            LawModel Model = new LawModel();

            Model.WebsiteId = 1;

            return View(Model);
        }

        public IActionResult Edit(int id)
        {
            if (!Authenticate.Check(_context, HttpContext))
            {
                return RedirectToAction("Logout", "Home");
            }


            var query = _context.Law.Where(a => a.Id == id).SingleOrDefault();

            if (query == null)
            {
                return RedirectToAction("Index");
            }

            LawModel Law = new LawModel
            {
                Id = query.Id,
                WebsiteId = query.WebsiteId,
                Title = query.Title,
                Slug = query.Slug,
                Icon = query.Icon,
                ShortDesc = query.ShortDesc,
                Description = query.Description,
            };
            return View(Law);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateLaw(LawModel law)
        {

            using (var context = new dbcopperheadContext())
            {
                var newlaw = new Law()
                {
                    Title = law.Title,
                    WebsiteId = law.WebsiteId,
                    Slug = law.Slug,
                    Icon = law.Icon,
                    ShortDesc = law.ShortDesc,
                    Description = law.Description
                };
                context.Law.Add(newlaw);
                context.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditLaw(LawModel law)
        {
            using (var context = new dbcopperheadContext())
            {

                var newlaw = new Law()
                {
                    Id = law.Id,
                    Title = law.Title,
                    WebsiteId = law.WebsiteId,
                    Slug = law.Slug,
                    Icon = law.Icon,
                    ShortDesc = law.ShortDesc,
                    Description = law.Description
                };
                context.Law.Update(newlaw);
                context.SaveChanges();
            }

            return RedirectToAction("Index");
        }

    }
}

admin.copperheadcreations.com/Views/Law/Create.cshtml
@model admin.copperheadcreations.com.Models.LawModel
<section class="button__container">
    <a asp-controller="Law" asp-action="Index" class="fancy__button fancy__button__dark button__spacer">Back</a>
</section>
<section class="container news__form">
    <form class="fancy__form color__grey bg__white" asp-action="CreateLaw" asp-controller="Law" method="post">

        <input asp-for="WebsiteId" hidden />

        <div class="form__row x30" id="Title">
            <input asp-for="Title" required />
            <label asp-for="Title"></label>
            <div class="after"></div>
        </div>
        <div class="form__row x30" id="Slug">
            <input asp-for="Slug" required />
            <label asp-for="Slug"></label>
            <div class="after"></div>
        </div>
        <p class="form__notes">
            Go to <a href="https://fontawesome.com/icons/">font awesome</a> and chose a non-pro icon, after selecting an icon there will be a string similar to  < i class="fas fa-ad"></ i> you need to copy the text between the quotes in this example: fas fa-ad
        </p>
        <div class="form__row x100">
            <input asp-for="Icon" required />
            <label asp-for="Icon"></label>
            <div class="after"></div>
        </div>


        <div class="form__row x100">
            <input asp-for="ShortDesc" required />
            <label asp-for="ShortDesc"></label>
            <div class="after"></div>
        </div>

        <textarea asp-for="Description" id="Editor-Content" hidden></textarea>

        <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">

        <!-- Create the editor container -->
        <div id="editor" class="form__editor">
            @Html.Raw(Model.Description)
        </div>
        <!-- Include the Quill library -->
        <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>

        <div class="form__row x10">
            <button>Submit</button>
        </div>

    </form>
</section>

admin.copperheadcreations.com/Views/Law/Edit.cshtml
@model admin.copperheadcreations.com.Models.LawModel
<section class="button__container">
    <a asp-controller="Law" asp-action="Index" class="fancy__button fancy__button__dark button__spacer">Back</a>
</section>
<section class="container news__form">
    <form class="fancy__form color__grey bg__white" asp-action="EditLaw" asp-controller="Law" method="post">

        <input asp-for="Id" hidden />
        <input asp-for="WebsiteId" hidden />

        <div class="form__row x30" id="Title">
            <input asp-for="Title" required />
            <label asp-for="Title"></label>
            <div class="after"></div>
        </div>
        <div class="form__row x30" id="Slug">
            <input asp-for="Slug" required />
            <label asp-for="Slug"></label>
            <div class="after"></div>
        </div>

        <div class="form__row x100">
            <input asp-for="Icon" required />
            <label asp-for="Icon"></label>
            <div class="after"></div>
        </div>


        <div class="form__row x100">
            <input asp-for="ShortDesc" required />
            <label asp-for="ShortDesc"></label>
            <div class="after"></div>
        </div>

        <textarea asp-for="Description" id="Editor-Content" hidden></textarea>

        <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">

        <!-- Create the editor container -->
        <div id="editor" class="form__editor">
            @Html.Raw(Model.Description)
        </div>
        <!-- Include the Quill library -->
        <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>

        <div class="form__row x10">
            <button>Submit</button>
        </div>

    </form>
</section>

admin.copperheadcreations.com/Views/Law/Index.cshtml
@model admin.copperheadcreations.com.Models.LawViewModel


<section class="container button__container">
    <a class="generic_button" asp-controller="Law" asp-action="Create">Create New Law Topic</a>
</section>
<section class="container">
    <div class="table">
        <div class="table__row table__header">
            <div class="table__cell x40">Title</div>
            <div class="table__cell x40">Slug</div>
            <div class="table__cell x10">Icon</div>
            <div class="table__cell x10">Edit</div>
        </div>
        @foreach (var u in Model.List)
        {
            <div class="table__row">
                <div class="table__cell x40">@u.Title</div>
                <div class="table__cell x40">/@u.Slug</div>
                <div class="table__cell x10">
                    <i class="@u.Icon"></i>
                </div>
                <a asp-controller="Law" asp-action="Edit" asp-route-id="@u.Id" class="table__cell x10 generic_edit"><i class="fas fa-edit"></i></a>
            </div>
        }

    </div>
</section>
<style>
    .published {
        text-align: center;
    }
</style>