admin.copperheadcreations.com/Models/SplashViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace admin.copperheadcreations.com.Models
{
    public class SplashViewModel
    {
        public List<SplashModel> List { get; set; }
    }
}

admin.copperheadcreations.com/Controllers/SplashController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using admin.copperheadcreations.com.Logic;
using admin.copperheadcreations.com.Models;
using Microsoft.AspNetCore.Mvc;

namespace admin.copperheadcreations.com.Controllers
{
    public class SplashController : Controller
    {
        private readonly dbcopperheadContext _context;

        public SplashController(dbcopperheadContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            if (!Authenticate.Check(_context, HttpContext))
            {
                return RedirectToAction("Logout", "Home");
            }
            SplashViewModel Model = new SplashViewModel();

            List<SplashModel> list = new List<SplashModel>();

            var query = _context.Splash.Where(a => a.WebsiteId == 1);

            foreach (var row in query)
            {
                SplashModel SplashBlock = new SplashModel {
                    Id = row.Id,
                    WebsiteId = row.WebsiteId,
                    Title = row.Title,
                    Text = row.Text
                };

                list.Add(SplashBlock);
            }
            Model.List = list;
            return View(Model);
        }


        public IActionResult Create()
        {

            if (!Authenticate.Check(_context, HttpContext))
            {
                return RedirectToAction("Logout", "Home");
            }

            SplashModel Model = new SplashModel();

            Model.WebsiteId = 1;

            return View(Model);
        }

        public IActionResult Edit(int id)
        {
            if (!Authenticate.Check(_context, HttpContext))
            {
                return RedirectToAction("Logout", "Home");
            }


            var query = _context.Splash.Where(a => a.Id == id).SingleOrDefault();

            if (query == null)
            {
                return RedirectToAction("Index");
            }

            SplashModel Model = new SplashModel
            {
                Id = query.Id,
                WebsiteId = query.WebsiteId,
                Title = query.Title,
                Text = query.Text
            };
            return View(Model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateSplash(SplashModel splash)
        {

            using (var context = new dbcopperheadContext())
            {
                var box = new Splash()
                {
                    Title = splash.Title,
                    WebsiteId = splash.WebsiteId,
                    Text = splash.Text
                };
                context.Splash.Add(box);
                context.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditSplash(SplashModel splash)
        {
            using (var context = new dbcopperheadContext())
            {

                var box = new Splash()
                {
                    Id = splash.Id,
                    Title = splash.Title,
                    WebsiteId = splash.WebsiteId,
                    Text = splash.Text
                };
                context.Splash.Update(box);
                context.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            if (!Authenticate.Check(_context, HttpContext))
            {
                return RedirectToAction("Logout", "Home");
            }

            var box = _context.Splash.Where(b => b.Id == id).FirstOrDefault();
            if (box != null)
            {
                using (var context = new dbcopperheadContext())
                {
                    context.Splash.Remove(box);
                    context.SaveChanges();
                }
            }


            return RedirectToAction("Index");
        }

    }
}

admin.copperheadcreations.com/Views/Splash/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@model admin.copperheadcreations.com.Models.SplashModel
<section class="button__container">
    <a asp-controller="Splash" asp-action="Index" class="fancy__button fancy__button__dark button__spacer">Back</a>
</section>
<section class="container news__form">
    <form class="fancy__form color__grey bg__white" asp-action="CreateSplash" asp-controller="Splash" method="post">

        <input asp-for="WebsiteId" hidden />

        <div class="form__row x30" id="Title">
            <input asp-for="Title" required />
            <label asp-for="Title"></label>
            <div class="after"></div>
        </div>
        <textarea asp-for="Text" id="Editor-Content" hidden></textarea>

        <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">

        <!-- Create the editor container -->
        <div id="editor" class="form__editor">
            @Html.Raw(Model.Text)
        </div>
        <!-- Include the Quill library -->
        <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>

        <div class="form__row x10">
            <button>Submit</button>
        </div>

    </form>
</section>

admin.copperheadcreations.com/Views/Splash/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@model admin.copperheadcreations.com.Models.SplashModel
<section class="button__container">
    <a asp-controller="Splash" asp-action="Index" class="fancy__button fancy__button__dark button__spacer">Back</a>
</section>
<section class="container news__form">
    <form class="fancy__form color__grey bg__white" asp-action="EditSplash" asp-controller="Splash" method="post">
        <input asp-for="Id" hidden />
        <input asp-for="WebsiteId" hidden />

        <div class="form__row x30" id="Title">
            <input asp-for="Title" required />
            <label asp-for="Title"></label>
            <div class="after"></div>
        </div>
        <textarea asp-for="Text" id="Editor-Content" hidden></textarea>

        <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">

        <!-- Create the editor container -->
        <div id="editor" class="form__editor">
            @Html.Raw(Model.Text)
        </div>
        <!-- Include the Quill library -->
        <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>

        <div class="form__row x10">
            <button>Submit</button>
        </div>

    </form>
</section>

admin.copperheadcreations.com/Views/Splash/Index.cshtml
@model admin.copperheadcreations.com.Models.SplashViewModel


<section class="container button__container">
    <a class="generic_button" asp-controller="Splash" asp-action="Create">Create New Splash Box</a>
</section>
<section class="container">
    <div class="table">
        <div class="table__row table__header">
            <div class="table__cell x40">Title</div>
            <div class="table__cell x40">Text</div>
            <div class="table__cell x10">Edit</div>
            <div class="table__cell x10">Delete</div>
        </div>
        @foreach (var u in Model.List)
        {
            <div class="table__row">
                <div class="table__cell x40">@u.Title</div>
                <div class="table__cell x40">@u.Text</div>
                <a asp-controller="Splash" asp-action="Edit" asp-route-id="@u.Id" class="table__cell x10 generic_edit"><i class="fas fa-edit"></i></a>
                <a asp-controller="Splash" asp-action="Delete" asp-route-id="@u.Id" class="table__cell x10 generic_delete"><i class="fas fa-trash-alt"></i></a>
            </div>
        }

    </div>
</section>
<style>
</style>